/serial_parser:
  ros__parameters:
    port_name: "/dev/ttyACM0"
    baud_rate: 115200

/localisation_engine_node:
  ros__parameters:
    # anchor_2, anchor_3, anchor_4
    anchor_positions_param: [0.0, 0.0, 1.0, 4.0, 0.0, 1.0, 0.0, 4.0, 1.0]

/mqtt_publihser_node:
  ros__parameters:
    mqtt_host: "10.98.186.228"



/mqtt_subscriber_node:
  ros__parameters:
    mqtt_host: "localhost"